export const actionsTypes = {
    INPUT: "INPUT",
    OPERATOR_ADD: "OPERATOR_ADD",
    OPERATOR_MINUS: "OPERATOR_MINUS",
    OPERATOR_DIVIDE: "OPERATOR_DIVIDE",
    OPERATOR_TIMES: "OPERATOR_TIMES"
}